name: Update Profile README

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Указываем нужную версию Python

      - name: Run Python script
        run: |
          python update_readme.py # Запускаем наш скрипт

      - name: Force Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git reset --soft HEAD~1 || true
          git add README.md
          git commit -m "🤖 Робот запустил Python-скрипт" --allow-empty
          git push --force origin main
